### ISSUE TITLE
Transform direction is set in radians whereas AndEndine uses degrees

### ISSUE THREAD

**Issue by AftonTroll** [AftonTroll/Avoidance#4]
This results in that the direction is barely changed at all

**Comment by FlorianMinges** [comment]
Question: Do we want to store the value in degrees then, or should we convert it every time? Should be more efficient to store the degree-value I guess.

**Comment by AftonTroll** [comment]
The calculations with the math class uses radians. As the math class is used more than the conversion at the rendering, using radians would actually be more efficient.FlorianMinges  skrev:>Question: Do we want to store the value in degrees then, or should we convert it every time? Should be more efficient to store the degree-value I guess.
