### ISSUE TITLE
There's still a process running after exiting the app

### ISSUE THREAD

**Issue by AftonTroll** [AftonTroll/Avoidance#6]
Annoying process that isn't used for anything.
What is causing it?/How to remove it?

**Comment by FlorianMinges** [comment]
When we receive the "QUIT_GAME"-event, we call the BaseGameActivitys finish()-method.
I have seen a different approach (with something like process/kill or something, not related to any BaseGameActivity-method) that should do the trick, but I'll probably have to google that.

**Comment by FlorianMinges** [comment]
Maybe it's not that straight forward anyways...
http://stackoverflow.com/questions/2033914/quitting-an-application-is-that-frowned-upon
